#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-ssl-config
Version  : 0.4.0
Release  : 1
URL      : https://github.com/lightbend/ssl-config/archive/v0.4.0.tar.gz
Source0  : https://github.com/lightbend/ssl-config/archive/v0.4.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/typesafe/ssl-config-core_2.11/0.2.1/ssl-config-core_2.11-0.2.1.jar
Source2  : https://repo.maven.apache.org/maven2/com/typesafe/ssl-config-core_2.11/0.2.1/ssl-config-core_2.11-0.2.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-ssl-config-data = %{version}-%{release}

%description
SSL Config
==========
<a href="https://travis-ci.org/lightbend/ssl-config"><img src="https://travis-ci.org/lightbend/ssl-config.svg"/></a>

%package data
Summary: data components for the mvn-ssl-config package.
Group: Data

%description data
data components for the mvn-ssl-config package.


%prep
%setup -q -n ssl-config-0.4.0

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/ssl-config-core_2.11/0.2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/ssl-config-core_2.11/0.2.1/ssl-config-core_2.11-0.2.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/typesafe/ssl-config-core_2.11/0.2.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/typesafe/ssl-config-core_2.11/0.2.1/ssl-config-core_2.11-0.2.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/typesafe/ssl-config-core_2.11/0.2.1/ssl-config-core_2.11-0.2.1.jar
/usr/share/java/.m2/repository/com/typesafe/ssl-config-core_2.11/0.2.1/ssl-config-core_2.11-0.2.1.pom
